name: test
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2      
    - name: test install_desktop.sh
      run : |
        ./install_desktop.sh default
