name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu:18.02

    steps:
    - name: create test user
      run: |
        useradd -ms /bin/bash test
        echo \"test ALL=(ALL) NOPASSWD: ALL\" >>/etc/sudoers
        mkdir -m 755 -p /home/test/.ssh && touch /home/test/.ssh/id_rsa.pub
    - name: test install script
      run : |
        su -s /bin/bash -c './install_desktop.sh default' test
